# Generated by Django 2.2.7 on 2019-11-07 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoastnRoast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boast', models.BooleanField()),
                ('message', models.CharField(max_length=280)),
                ('upvote', models.IntegerField(default=0)),
                ('downvote', models.IntegerField(default=0)),
                ('post_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
