# Generated by Django 2.2.7 on 2019-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost', '0002_auto_20191107_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastnroast',
            name='total_votes',
            field=models.IntegerField(default=0),
        ),
    ]
