# Generated by Django 2.2.7 on 2019-11-11 13:57

from django.db import migrations, models
import ghostPost.models


class Migration(migrations.Migration):

    dependencies = [
        ('ghostPost', '0003_boastnroast_total_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='boastnroast',
            name='secret_code',
            field=models.CharField(default=ghostPost.models.random_string, max_length=6),
        ),
    ]
